Documents/GuidingPrinciples.md
Add a principle that allows duplicate representations of the same information to be present, as long as they are consistent.
=> Guiding principles: allow duplicate representations.

Agendas/20180314.md
=> Update proposed agenda per TC discussion

Documents/ChangeDrafts/Active/graphs.txt, Documents/ChangeDrafts/Active/locations.txt
Update various checked in documents and design proposals in advance of TC #13.
@lgolding fyi
=> add proposal text files for graphs and location changes

Schemata/sarif-schema.json
- #174: `result.occurrences`
- #233: Optional `rule.id`
- #237: `result.graphs` and `run.graphs` are dictionaries.
=> Schema changes for #174, #233, and #237.

Schemata/sarif-2.0.0-csd.2.beta.2018-10-10.json
=> Check in sarif-2.0.0-csd.2.beta.2018-10-10 schema

Schemata/sarif-2.0.0-csd.2.beta.2019-01-24.json
=> Add v2.0.0-csd.2.beta.2019-01-24.1 schema

Plans.md
We are back on track to continue moving SARIF v2.1.0 toward a standard.  This change updates our status tracker to reflect where we are now.
=> Update SARIF status to reflect current progress

Plans.md
This updates our project status document to reflect the fact that we are now in the 60-day public comment period.
=> Update project status 2020-01

meeting_minutes/211209_SARIF_TC_49.md
~Links to agenda and previous minutes draft not yet filled in~
This is now the post-meeting minutes document.
=> Minutes for Meeting 2021-12-09

meeting_minutes/220113_SARIF_TC_50.md
To approve during the TC meeting today 2022-01-27
=> Added missing participant entry

meeting_minutes/220210_SARIF_TC_52.md
Meeting preparation phase PR.
Question: where can I find the minutes to weave into this document?
=> Meeting 20220210

Documents/IanaRegistrations/sarif-external-properties-media-type.txt, Documents/IanaRegistrations/sarif-media-type.txt, Documents/IanaRegistrations/sarif-uri-scheme.txt
Fixes #503
Is there an additional need to fix downstream (on IANA side)?
=> Fixes of two URLs in IANA registration

meeting_minutes/220224_SARIF_TC_53.md
=> Minutes of meeting 2022-FEB-24

meeting_minutes/220324_SARIF_TC_55.md, meeting_minutes/220407_SARIF_TC_56.md
While I was producing the 2022-APR-07 minute draft, I created this PR en passant - hope it helps.
=> Amending the minutes from 2022-MAR-24

Documents/WorkingNotes/SarifStoreUseCases.md
Working notes drafted for TC meeting #57. @dmk42 @sthagen @easyrhinomsft
=> Add SARIF store use case notes.

meeting_minutes/220421_SARIF_TC_57.md
=> Initial agenda aligned minutes (before meeting)

meeting_minutes/220505_SARIF_TC_58.md
=> Meeting prep for 20220505

meeting_minutes/20220930_SARIF_TC_61.md
Please kindly review so we can fix any errors introduced and merge well before the next meeting.
=> Meeting minutes 2022-06-30

meeting_minutes/220728_SARIF_TC_63.md
=> Notes of SARIF TC meeting 2022-JUL-28

meeting_minutes/220811_SARIF_TC_64.md
=> Draft meeting minutes of 2022-08-11 (no. 64)

meeting_minutes/220915_SARIF_TC_66.md
=> Meeting Minutes 2022-09-15

meeting_minutes/220929_SARIF_TC_67.md
=> Meeting minutes 2022-SEP-29

meeting_minutes/221013_SARIF_TC_68.md
=> Minutes of meeting 2022-OCT-13

meeting_minutes/221110_SARIF_TC_70.md
=> Minutes of meeting 2022-11-10

meeting_minutes/221208_SARIF_TC_71.md
These are Thanassis' minutes (thanks!), which I have put into the usual format.
=> Minutes from 2022-12-08

meeting_minutes/230308_SARIF_TC_73.md
Version of draft minutes to review.
=> Meeting minutes for TC meeting 2023-MAR-09

meeting_minutes/230420_SARIF_TC_74.md
Please kindly review the minutes of meeting 2023-APR-20
=> Initial minutes template 2023-APR-20

meeting_minutes/230525_SARIF_TC_75.md
Status: Template for the upcoming meeting.
=> Meeting minutes draft 2023-MAY-25

meeting_minutes/230713_SARIF_TC_77.md
After the meeting the document will receive updates and the PR will leave draft mode.
=> Seed document for meeting minutes 2023-JUL-13

meeting_minutes/230810_SARIF_TC_78.md
=> Meeting minutes 2023-AUG-10

Future.md
small changes to test pull request
=> corrected error in markdown / corrected grammar

meeting_minutes/230914_SARIF_TC_79.md
=> Meeting minutes of 2023-09-14

meeting_minutes/231012_SARIF_TC_80.md
=> Meeting minutes 2023-10-12

meeting_minutes/231109_SARIF_TC_81.md
=> Minutes draft for TC meeting #81 on 2023-11-09

Schemata/sarif-external-property-file-schema-2.1.0.json, Schemata/sarif-schema-2.1.0.json
=> Update the github copies of the schemata to match the Approved Errata

meeting_minutes/231207_SARIF_TC_82.md
=> Meeting 2023-12-07 minutes

meeting_minutes/240111_SARIF_TC_83.md
=> Meeting 2024-01-11 minutes draft

Future.md
Minor tweak requested by the group at the previous meeting.
=> Add Future.md Purpose and Objectives headings as agreed at February meeting

meeting_minutes/240307_SARIF_TC_85.md
=> Meeting minutes for 2024-03-07

meeting_minutes/240404_SARIF_TC_86.md
=> Meeting 2024-04-04 minutes

meeting_minutes/240606_SARIF_TC_88.md
=> Meeting minutes 2024-06-06

meeting_minutes/240711_SARIF_TC_89.md
=> Meeting minutes for 2024-07-11

sarif-2.2/prose/edit/src/file-format-24-artifact-object.md
=> Fixed #634 duplicated notes enumeration

sarif-2.2/prose/edit/src/file-format-24-artifact-object.md, sarif-2.2/schema/sarif-2-2.schema.json
=> Defined a scanned file role (#459)

sarif-2.2/prose/edit/src/file-format-09-datetime-properties.md
=> Implemented expiry date utc example additions (#492)

sarif-2.2/prose/edit/etc/section-display-to-label.json, sarif-2.2/prose/edit/etc/section-label-to-display.json, sarif-2.2/prose/edit/src/file-format-58-notification-object.md, sarif-2.2/schema/sarif-2-2.schema.json
=> Added related locations property (#491)

meeting_minutes/240808_SARIF_TC_90.md
=> Meeting 2024-08-08

meeting_minutes/240905_SARIF_TC_91.md
=> Meeting 2024-09-05

meeting_minutes/241010_SARIF_TC_92.md
Note: After merge and approval the link per OASIS systems will be:
* [Minutes of 2024-10-10 Meeting #92](https://www.oasis-open.org/committees/download.php/72271/)
=> Minutes of meeting 2024-10-10

meeting_minutes/241212_SARIF_TC_94.md
These are the minutes provided by Thanassis (Thanks!), with very minor edits.
=> Minutes of Meeting 2024-12-12

meeting_minutes/250109_SARIF_TC_95.md
=> Meeting 2025-01-09

sarif-2.2/prose/edit/src/file-format-38-threadflowlocation-object.md
Implements #530.
Co-authored-by: David Malcolm <dmalcolm@redhat.com>
Signed-off-by: Stefan Hagen <stefan@hagen.link>
=> Editor Proposal for 530 Thread Flow Location Additions

sarif-2.2/prose/edit/src/file-format-33-logicallocation-object.md
Implements #670.
Co-authored-by: David Malcolm <dmalcolm@redhat.com>
Signed-off-by: Stefan Hagen <stefan@hagen.link>
=> Editorial Proposal to Fix JSON Example for logicalLocation/kind

meeting_minutes/250206_SARIF_TC_96.md
=> Meeting minutes 2025-02-06

sarif-2.2/prose/edit/src/file-format-35-suppression-object.md
Implements #574.
Signed-off-by: Stefan Hagen <stefan@hagen.link>
=> Editor Proposal for 574 adding a justification enumeration

meeting_minutes/250306_SARIF_TC_97.md
=> Meeting minutes of 2025-03-06

meeting_minutes/250410_SARIF_TC_98.md
=> Meeting minutes 2025-04-10

meeting_minutes/250515_SARIF_TC_99.md
=> Minutes of meeting 2025-05-15

sarif-2.2/prose/edit/src/introduction-02-terminology-glossary.md
Reverts oasis-tcs/sarif-spec#709
=> Revert "Amended glossary with term: "analysis tool""

meeting_minutes/250710_SARIF_TC_101.md
=> Meeting minutes 2025-07-10

meeting_minutes/250807_SARIF_TC_102.md
=> Meeting minutes 2025-08-07
